apiVersion: v1
kind: Service
metadata:
  name: {{ include "makely.fullname" . }}
  labels:
    {{- include "makely.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: "34.133.4.218"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "makely.selectorLabels" . | nindent 4 }}