apiVersion: v1
kind: Service
metadata:
  name: {{ include "makely.fullname" . }}
  labels:
    {{- include "makely.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "makely.selectorLabels" . | nindent 4 }}