name: Deploy
on:
  repository_dispatch:
    types: [Deploy]
  push:
    branches:
      - master
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: us-central1-c
    
jobs:
  deployment:
    environment: production
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    - name: Deploy
      uses: WyriHaximus/github-action-helm3@v2
      with:
        exec: helm upgrade makely makely --set image.repository=${{ github.event.client_payload.image }} --set image.tag=${{ github.event.client_payload.tag }} --set env.secretKey=${{ secrets.SECRET_KEY }} --set env.secretKey=${{ secrets.DB_CONNECTION }}